//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDatabaseFirst.DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SomeDbEntities : DbContext
    {
        public SomeDbEntities()
            : base("name=SomeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentparent> studentparents { get; set; }
        public virtual DbSet<studentparentnew> studentparentnews { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<Personal1> Personal1 { get; set; }
        public virtual DbSet<Personal_Backup> Personal_Backup { get; set; }
        public virtual DbSet<vw_FullDetails> vw_FullDetails { get; set; }
    }
}
