//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDatabaseFirst.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentparentnew
    {
        public int id { get; set; }
        public int studentid { get; set; }
        public int parentid { get; set; }
    
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
    }
}
